### ISSUE TITLE
mugen format file compile error.

### ISSUE THREAD

**Issue by fastfading** [kazzmir/paintown#12]
I have test many mugen characters ,   they all run well on mugen and ikemen
But when it comes to paintown, it report many errors.
Almost 85% of win mugen (mugenversion=xx.xx.2001 or xx.xx.2002) characters  reports errors
I notice that most of the errors are actually mugen file error, not the paintown engine.
For many characters are fan made, nearly all of them are full of bugs.
I guess the mugen engine tolerate more errors than paintown . 

So I think if there is a way to let paintown tolerate errors , not throw exception. And how ?
I guess 1 line error in mugen format files will not affect the game.
And are there any tested  mugen characters collection  to download?

**Comment by EvilQU3S4D1LL4S** [comment]
Yes I compiled several downloaded characters and stages for testing some are error free like the obvious ones KFM versions and also Kung Fu Fan Akuma character although projectiles and specials and other effects dont work.. since is different  from the pc version of WinMugen and ctds on other modes paintown has.. comment if you want a couple of this characters.. Mb limit of paintown is about 2.50mb of characters if over the limit game slows down alot or lag freeze.

**Comment by EvilQU3S4D1LL4S** [comment]
I forgot to say most Motifs don't work hard to find a very simple Motif to use like 100 chars or Over for paintown. Characters are in Mega

**Comment by juvinious** [comment]
The paintown implementation was aimed to support content prior to the rc1 1.0 release in 2009.

I assume that most MUGEN content floating around today has probably been updated to support 1.0 and further which fails to load or works horribly in the current paintown implementation.
