### ISSUE TITLE
Legal issues

### ISSUE THREAD

**Issue by sagitter** [kazzmir/paintown#23]
Hello everyone.

Legal notes (following related web-chat discussion on http://webchat.freenode.net/?randomnick=1&channels=paintown) about current Paintown source archive's content:

- [ ] - Paintown code provides a LEGAL file that it's incomplete but important for providing full note about **all** data files included (fonts, images, icons, ...)

- [ ] It seems available a [separated **data** archive](https://github.com/kazzmir/paintown/releases/download/v3.6.0/data-3.6.0.zip) with additional characters but without any explicit legal note about its content. Since this archive provides special non-free copies of sprites from other games (see https://bugzilla.redhat.com/show_bug.cgi?id=1562832), a specific LEGAL file should be put to attention of the user regarding the related consequences.

- [ ] Is Paintown playable without separated archived data?

**Comment by juvinious** [comment]
To answer your questions:

> - [x] - Paintown code provides a LEGAL file that it's incomplete but important for providing full note about **all** data files included (fonts, images, icons, ...)

* kazzmir/paintown@ec5824f fixes the LEGAL document and addresses the data directory in this repository.

> - [x] It seems available a [separated **data** archive](https://github.com/kazzmir/paintown/releases/download/v3.6.0/data-3.6.0.zip) with additional characters but without any explicit legal note about its content. Since this archive provides special non-free copies of sprites from other games (see https://bugzilla.redhat.com/show_bug.cgi?id=1562832), a specific LEGAL file should be put to attention of the user regarding the related consequences.

* The new LEGAL.md should cover that in the initial paragraph. In other words do not bundle the data-3.6.0.zip within the distribution

> - [x] Is Paintown playable without separated archived data?

* The current data directory within the repository is enough to get the game to run the main menu. This excludes any levels or characters so that would have to be added separately. For legal purposes I would say that it is sufficient and people can just google paintown to find the extra data if they want to play.
